export type ServiceStatus = "draft" | "published" | "disabled";

/**
 * How the Varis gateway calls your endpoint. Agents always call Varis the
 * same way; this is the request your endpoint receives.
 *
 * - `GET`: the input arrives as query parameters, so `Input` must be flat:
 *   strings, numbers, booleans, literal unions, and arrays of those. Numbers
 *   and booleans arrive as strings.
 * - `POST`: the input arrives as a JSON body, so `Input` can nest.
 */
export type ServiceMethod = "GET" | "POST";

export interface ServiceDefinition {
  /** Unique within your owner, and permanent. Use lowercase words joined by hyphens. */
  slug: string;
  name: string;
  /** Description must be between 20 and 1024 characters. Agents read this to decide whether to call this service. */
  description: string;
  service_type: ServiceType;
  /** At least one category slug from the platform's closed list. Categories tell agents what domain the service covers. */
  categories: ServiceCategory[];
  /** Must be HTTPS and publicly reachable, with no query string. */
  endpoint_url: string;
  /**
   * How the gateway calls `endpoint_url`. Defaults to "GET", which needs a
   * flat `Input`. Use "POST" for nested input, or for input that shouldn't
   * appear in access logs.
   */
  method?: ServiceMethod;
  /** Price per request, in US cents. Zero makes the service free. */
  price_cents: number;
  /** Recorded, not resolved. Defaults to "1.0.0". */
  version?: string;
  /** Defaults to "published". */
  status?: ServiceStatus;
}

export type ServiceType =
  | "data"
  | "content"
  | "tool"
  | "skill"
  | "compute"
  | "memory"
  | "storage"
  | "model"
  | "messaging";

/** Closed list mirrored in openapi.yaml (ServiceCategory). Adding a value is safe, renaming one is not. */
export type ServiceCategory =
  | "accounting"
  | "advertising"
  | "aerospace"
  | "agents"
  | "agriculture"
  | "ai"
  | "analytics"
  | "animation"
  | "apis"
  | "architecture"
  | "art"
  | "astrology"
  | "astronomy"
  | "audio"
  | "audio-processing"
  | "authentication"
  | "automation"
  | "automotive"
  | "aviation"
  | "banking"
  | "beauty"
  | "biology"
  | "biotech"
  | "blockchain"
  | "books"
  | "branding"
  | "browser-automation"
  | "business-intelligence"
  | "calendar"
  | "careers"
  | "census"
  | "charity"
  | "chemistry"
  | "civil-engineering"
  | "climate"
  | "clinical-trials"
  | "cloud"
  | "code-generation"
  | "code-review"
  | "collaboration"
  | "comics"
  | "commodities"
  | "compliance"
  | "computer-vision"
  | "construction"
  | "consulting"
  | "contracts"
  | "copywriting"
  | "credit"
  | "crm"
  | "crypto"
  | "culture"
  | "customer-support"
  | "databases"
  | "datasets"
  | "dating"
  | "defense"
  | "demographics"
  | "design"
  | "developer-tools"
  | "devops"
  | "diy"
  | "documents"
  | "earth-science"
  | "ecology"
  | "ecommerce"
  | "economics"
  | "education"
  | "elections"
  | "electrical-engineering"
  | "email"
  | "embeddings"
  | "employment"
  | "energy"
  | "entertainment"
  | "environment"
  | "esports"
  | "evaluation"
  | "events"
  | "family"
  | "fashion"
  | "file-conversion"
  | "film"
  | "finance"
  | "fitness"
  | "food"
  | "forex"
  | "fraud-detection"
  | "gaming"
  | "gardening"
  | "genealogy"
  | "genomics"
  | "geolocation"
  | "geopolitics"
  | "geospatial"
  | "governance"
  | "government"
  | "graphic-design"
  | "hardware"
  | "health"
  | "healthcare"
  | "higher-education"
  | "history"
  | "home"
  | "hospitality"
  | "housing"
  | "human-resources"
  | "human-rights"
  | "humor"
  | "identity-verification"
  | "image-generation"
  | "image-processing"
  | "immigration"
  | "infrastructure"
  | "insurance"
  | "intellectual-property"
  | "international-relations"
  | "inventory"
  | "investing"
  | "invoicing"
  | "iot"
  | "journalism"
  | "k12"
  | "knowledge-base"
  | "kyc"
  | "language-learning"
  | "law-enforcement"
  | "legal"
  | "lending"
  | "lifestyle"
  | "llm"
  | "localization"
  | "logistics"
  | "machine-learning"
  | "manufacturing"
  | "maps"
  | "maritime"
  | "market-research"
  | "marketing"
  | "marketplace"
  | "materials-science"
  | "mathematics"
  | "mechanical-engineering"
  | "media"
  | "medical-imaging"
  | "medicine"
  | "mental-health"
  | "military"
  | "mobile-development"
  | "monitoring"
  | "mortgage"
  | "music"
  | "networking"
  | "news"
  | "nlp"
  | "nonprofit"
  | "notifications"
  | "nutrition"
  | "observability"
  | "ocr"
  | "oil-and-gas"
  | "open-data"
  | "open-source"
  | "outdoors"
  | "parenting"
  | "patents"
  | "payments"
  | "payroll"
  | "pdf"
  | "personal-finance"
  | "pets"
  | "pharmaceuticals"
  | "philosophy"
  | "photography"
  | "physics"
  | "podcasts"
  | "policy"
  | "politics"
  | "pricing"
  | "privacy"
  | "procurement"
  | "productivity"
  | "project-management"
  | "prompts"
  | "psychology"
  | "public-health"
  | "public-records"
  | "public-relations"
  | "public-safety"
  | "public-transit"
  | "publishing"
  | "quantum-computing"
  | "real-estate"
  | "recipes"
  | "recruiting"
  | "reference"
  | "relationships"
  | "religion"
  | "renewable-energy"
  | "research"
  | "restaurants"
  | "retail"
  | "robotics"
  | "sales"
  | "sanctions"
  | "scheduling"
  | "science"
  | "scraping"
  | "search"
  | "security"
  | "semiconductors"
  | "seo"
  | "shipping"
  | "shopping"
  | "small-business"
  | "sms"
  | "social-media"
  | "sociology"
  | "software-engineering"
  | "space"
  | "speech"
  | "sports"
  | "startups"
  | "statistics"
  | "stocks"
  | "supply-chain"
  | "sustainability"
  | "tax"
  | "telecommunications"
  | "television"
  | "testing"
  | "text-to-speech"
  | "ticketing"
  | "time-series"
  | "trading"
  | "transcription"
  | "translation"
  | "transportation"
  | "travel"
  | "ui-design"
  | "urban-planning"
  | "utilities"
  | "vector-search"
  | "venture-capital"
  | "veterinary"
  | "video"
  | "video-processing"
  | "weather"
  | "web-development"
  | "web3"
  | "wellness"
  | "writing";
